"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional, Tuple, Type, Union
from django.db.models import Model
from ninja.schema import Schema

__all__ = ["SchemaFactory", "factory", "create_schema"]
SchemaKey = Tuple[Type[Model], str, int, str, str, str]
class SchemaFactory:
    def __init__(self) -> None:
        ...
    
    def create_schema(self, model: Type[Model], *, name: str = ..., depth: int = ..., fields: Optional[List[str]] = ..., exclude: Optional[List[str]] = ..., custom_fields: Optional[List[Tuple[str, Any, Any]]] = ..., base_class: Type[Schema] = ...) -> Type[Schema]:
        ...
    
    def get_key(self, model: Type[Model], name: str, depth: int, fields: Union[str, List[str], None], exclude: Optional[List[str]], custom_fields: Optional[List[Tuple[str, str, Any]]]) -> SchemaKey:
        "returns a hashable value for all given parameters"
        ...
    


factory = ...
create_schema = ...
