"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, Generator, Tuple, Type, TypeVar, no_type_check
from django.db.models.fields import Field
from ninja.openapi.schema import OpenAPISchema

__all__ = ["create_m2m_link_type", "get_schema_field", "get_related_field_schema"]
class AnyObject:
    @classmethod
    def __modify_schema__(cls, field_schema: Dict[str, Any]) -> None:
        ...
    
    @classmethod
    def __get_validators__(cls) -> Generator[Callable, None, None]:
        ...
    
    @classmethod
    def validate(cls, value: Any) -> Any:
        ...
    


TYPES = ...
TModel = TypeVar("TModel")
@no_type_check
def create_m2m_link_type(type_: Type[TModel]) -> Type[TModel]:
    class M2MLink(type_):
        ...
    
    

@no_type_check
def get_schema_field(field: Field, *, depth: int = ...) -> Tuple:
    ...

@no_type_check
def get_related_field_schema(field: Field, *, depth: int) -> Tuple[OpenAPISchema]:
    ...

