"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Any, Optional
from django.http import HttpRequest
from ninja.security.base import AuthBase

__all__ = ["APIKeyBase", "APIKeyQuery", "APIKeyCookie", "APIKeyHeader"]
class APIKeyBase(AuthBase, ABC):
    openapi_type: str = ...
    param_name: str = ...
    def __init__(self) -> None:
        ...
    
    def __call__(self, request: HttpRequest) -> Optional[Any]:
        ...
    
    @abstractmethod
    def authenticate(self, request: HttpRequest, key: Optional[str]) -> Optional[Any]:
        ...
    


class APIKeyQuery(APIKeyBase, ABC):
    openapi_in: str = ...


class APIKeyCookie(APIKeyBase, ABC):
    openapi_in: str = ...


class APIKeyHeader(APIKeyBase, ABC):
    openapi_in: str = ...


