"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Any, Optional
from django.http import HttpRequest

__all__ = ["SecuritySchema", "AuthBase"]
class SecuritySchema(dict):
    def __init__(self, type: str, **kwargs: Any) -> None:
        ...
    


class AuthBase(ABC):
    def __init__(self) -> None:
        ...
    
    @abstractmethod
    def __call__(self, request: HttpRequest) -> Optional[Any]:
        ...
    


