"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Any, Optional, Tuple
from django.http import HttpRequest
from ninja.security.base import AuthBase

__all__ = ["HttpAuthBase", "HttpBearer", "DecodeError", "HttpBasicAuth"]
logger = ...
class HttpAuthBase(AuthBase, ABC):
    openapi_type: str = ...


class HttpBearer(HttpAuthBase, ABC):
    openapi_scheme: str = ...
    header: str = ...
    def __call__(self, request: HttpRequest) -> Optional[Any]:
        ...
    
    @abstractmethod
    def authenticate(self, request: HttpRequest, token: str) -> Optional[Any]:
        ...
    


class DecodeError(Exception):
    ...


class HttpBasicAuth(HttpAuthBase, ABC):
    openapi_scheme = ...
    header = ...
    def __call__(self, request: HttpRequest) -> Optional[Any]:
        ...
    
    @abstractmethod
    def authenticate(self, request: HttpRequest, username: str, password: str) -> Optional[Any]:
        ...
    
    def decode_authorization(self, value: str) -> Tuple[str, str]:
        ...
    


