"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict

__all__ = ["NOT_SET"]
class NOT_SET_TYPE:
    def __repr__(self) -> str:
        ...
    
    def __copy__(self) -> Any:
        ...
    
    def __deepcopy__(self, memodict: Dict = ...) -> Any:
        ...
    


NOT_SET = ...
