"""
This type stub file was generated by pyright.
"""

from typing import List, TYPE_CHECKING
from ninja.types import DictStrAny
from ninja import NinjaAPI

if TYPE_CHECKING:
    ...
__all__ = ["ConfigError", "AuthenticationError", "ValidationError", "HttpError", "set_default_exc_handlers"]
logger = ...
class ConfigError(Exception):
    ...


class AuthenticationError(Exception):
    ...


class ValidationError(Exception):
    """
    This exception raised when operation params do not validate
    Note: this is not the same as pydantic.ValidationError
    the errors attribute as well holds the location of the error(body, form, query, etc.)
    """
    def __init__(self, errors: List[DictStrAny]) -> None:
        ...
    


class HttpError(Exception):
    def __init__(self, status_code: int, message: str) -> None:
        ...
    


def set_default_exc_handlers(api: NinjaAPI) -> None:
    ...

