"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, Iterable, Optional, Type
from django.core.files.uploadedfile import UploadedFile as DjangoUploadedFile
from pydantic.fields import ModelField

__all__ = ["UploadedFile"]
class UploadedFile(DjangoUploadedFile):
    @classmethod
    def __get_validators__(cls: Type[UploadedFile]) -> Iterable[Callable[..., Any]]:
        ...
    
    @classmethod
    def __modify_schema__(cls, field_schema: Dict[str, Any], field: Optional[ModelField]) -> None:
        ...
    


