"""
This type stub file was generated by pyright.
"""

from typing import Any
from pydantic.fields import FieldInfo
from ninja import params_models

__all__ = ["Param", "Path", "Query", "Header", "Cookie", "Body", "Form", "File"]
class Param(FieldInfo):
    def __init__(self, default: Any, *, alias: str = ..., title: str = ..., description: str = ..., gt: float = ..., ge: float = ..., lt: float = ..., le: float = ..., min_length: int = ..., max_length: int = ..., regex: str = ..., deprecated: bool = ..., **extra: Any) -> None:
        ...
    


class Path(Param):
    _model = params_models.PathModel


class Query(Param):
    _model = params_models.QueryModel


class Header(Param):
    _model = params_models.HeaderModel


class Cookie(Param):
    _model = params_models.CookieModel


class Body(Param):
    _model = params_models.BodyModel


class Form(Param):
    _model = params_models.FormModel


class File(Param):
    _model = params_models.FileModel


class _MultiPartBody(Param):
    _model = params_models._MultiPartBodyModel
    _param_source = ...


