"""
This type stub file was generated by pyright.
"""

import json
from typing import Any, Mapping, Optional, Type
from django.http import HttpRequest

__all__ = ["BaseRenderer", "JSONRenderer"]
class BaseRenderer:
    media_type: Optional[str] = ...
    charset: str = ...
    def render(self, request: HttpRequest, data: Any, *, response_status: int) -> Any:
        ...
    


class JSONRenderer(BaseRenderer):
    media_type = ...
    encoder_class: Type[json.JSONEncoder] = ...
    json_dumps_params: Mapping[str, Any] = ...
    def render(self, request: HttpRequest, data: Any, *, response_status: int) -> Any:
        ...
    


