"""
This type stub file was generated by pyright.
"""

from typing import Callable, Optional
from django.http import HttpRequest, HttpResponseForbidden

__all__ = ["check_csrf", "is_debug_server", "normalize_path"]
def replace_path_param_notation(path: str) -> str:
    ...

def normalize_path(path: str) -> str:
    ...

def check_csrf(request: HttpRequest, callback: Callable) -> Optional[HttpResponseForbidden]:
    ...

def is_debug_server() -> bool:
    """Check if running under the Django Debug Server"""
    ...

