"""
This type stub file was generated by pyright.
"""

import django
from typing import Callable
from django.http import HttpRequest

class HttpHeaders(CaseInsensitiveMapping):
    HTTP_PREFIX = ...
    UNPREFIXED_HEADERS = ...
    def __init__(self, environ) -> None:
        ...
    
    def __getitem__(self, key):
        """Allow header lookup using underscores in place of hyphens."""
        ...
    
    @classmethod
    def parse_header_name(cls, header): # -> None:
        ...
    


def get_headers_old(request): # -> HttpHeaders:
    ...

def get_headers_v3(request):
    ...

get_headers: Callable[[HttpRequest], HttpHeaders]
if django.VERSION[0] < 3:
    get_headers = ...
else:
    get_headers = ...
