"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Optional, Union
from django.http import StreamingHttpResponse
from ninja import NinjaAPI, Router
from ninja.responses import Response as HttpResponse

def build_absolute_uri(location: Optional[str] = ...) -> str:
    ...

class NinjaClientBase:
    __test__ = ...
    def __init__(self, router_or_app: Union[NinjaAPI, Router]) -> None:
        ...
    
    def get(self, path: str, data: Dict = ..., **request_params: Dict) -> NinjaResponse:
        ...
    
    def post(self, path: str, data: Dict = ..., json: Any = ..., **request_params: Any) -> NinjaResponse:
        ...
    
    def patch(self, path: str, data: Dict = ..., json: Any = ..., **request_params: Any) -> NinjaResponse:
        ...
    
    def put(self, path: str, data: Dict = ..., json: Any = ..., **request_params: Any) -> NinjaResponse:
        ...
    
    def delete(self, path: str, data: Dict = ..., json: Any = ..., **request_params: Any) -> NinjaResponse:
        ...
    
    def request(self, method: str, path: str, data: Dict = ..., json: Any = ..., **request_params: Any) -> NinjaResponse:
        ...
    
    @property
    def urls(self) -> List:
        ...
    


class TestClient(NinjaClientBase):
    ...


class TestAsyncClient(NinjaClientBase):
    ...


class NinjaResponse:
    def __init__(self, http_response: Union[HttpResponse, StreamingHttpResponse]) -> None:
        ...
    
    def json(self) -> Any:
        ...
    
    def __getitem__(self, key: str) -> Any:
        ...
    
    def __getattr__(self, attr: str) -> Any:
        ...
    


